spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:postgresql://${}:${}/${}?useTimezone=true&serverTimezone=UTC
    username: root
    password:
  cache:
    type: redis
    #redis:
    # host: localhost
    #port: 6379
    #password:
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: secret
  expiration: 86400000